---
language: python
python: '2.7'
addons:
  sauce_connect:
  - username: $SAUCE_USERNAME
  - access_key: $SAUCE_ACCESS_KEY
install:
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
script: bin/test
env:
  global:
  - secure: ! 'Rnky1vmdbh5FIJQsWUhSnz/dmIVWLW8Km9vmAjyZs4mjUj8X/Nou8OrLe8bn
      JMdn+IHGb9S4yG8Sxu6OVDZcrlCtHUVQELRQ4tKBZqJtIe8aaCf5+ELCkqbg
      vLzumacZnf6Wp7VOFmsv0CSJeA6m3ItGfP4kdCTpXdwSoU4ycbs='
  - secure: ! 'jaNbVQuhwkj0TcQInVbBmQ6E4tvX7DhE90qWAsRoEDn/p3h5WRP3Mt8szN93
      mvFBisJuwtmMSDtnNn5cSZYlK6/BuRYt3xtVMIM9lLomUiK+9doFVYAo3rR+
      jqgeuuBEKBOQnaj2BDlLV1j9I+79YjTloCtBOKxwzINLPjcNyR4='
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
  matrix:
  - ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
  - ROBOT_BROWSER=ie ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID,version:6
  - ROBOT_DESIRED_CAPABILITIES="platform:OS X 10.8,browserName:iPad,version:6,tunnel-identifier:$TRAVIS_JOB_ID"
